spring:
    application:
        name: backend

    devtools:
      livereload:
        enabled: true

    profiles:
      active: env

server:
  port: 8080

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true